version: '3'

services:
  contextgenerator3:
    image: spencerjang/context:0.3
    deploy:
      placement:
        constraints:
          - node.hostname == spNode03

  contextgenerator4: 
    image: spencerjang/context:0.3
    deploy:
      placement:
        constraints:
          - node.hostname ==spNode04

  contextcollector1:
    image: spencerjang/collector:0.1
    deploy:
      placement:
        constraints:
          - node.hostname ==spNode01

