version: '3'

services:
  mastercontainer:
    image: spencerjang/resinwithoutenv:latest
    volumes:
      - myvol:/var/lib/docker/result
    deploy:
      placement:
        constraints: [node.hostname == spNode01]
      restart_policy:
        condition: on-failure
    networks:
      hyp:
        aliases:
          - con1
    command: ping -c 1000 google.com

  user1_task1_section1:
    image: spencerjang/resinwithoutenv:latest
    deploy:
      placement:
        constraints: [node.hostname == spNode02]
    networks:
      hyp:
        aliases:
          - con2
    command: ping -c 1000 google.com
  
  user1_task1_section2:
    image: spencerjang/resinwithoutenv:latest
    deploy:
      placement:
        constraints: [node.hostname == spNode04] 
    networks:
      hyp:
        aliases:
          - con4
    command: ping -c 1000 google.com

volumes:
  myvol:
networks:
  hyp:
