version: '3'

services:
  serv:
    image: spencerjang/javaserver:0.1
    ports:
      - 25000:25000
    networks:
      javanet:
        aliases:
          - serv 
    deploy:
      placement:
        constraints:
          - node.hostname == spNode01
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"] 
      timeout: 5s
      retries: 3

  app_3:
    image: spencerjang/javaclient:0.1
    depends_on:
      - serv
    networks:
      javanet:
        aliases:
          - node3
    deploy:
      placement:
        constraints:
          - node.hostname == spNode03

  app_4: 
    image: spencerjang/javaclient:0.1
    depends_on:
      - serv
    networks:
      javanet:
        aliases:
          - node4
    deploy:
      placement:
        constraints:
          - node.hostname ==spNode04
networks:
  javanet:
 
